In [ ]:
import pandas as pd
import numpy as np
import math

In [ ]:
train_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/train.csv"
train = pd.read_csv(train_url) #training set
test_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/test.csv"
test = pd.read_csv(test_url) #test set

In [ ]:
print("T8) median is "+str(train["Age"].median()))
#print("mode is "+str(train["Age"].mode()[0]))

train["Age"] = train["Age"].fillna(train["Age"].median())
print(train["Survived"])


T8) median is 28.0
0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64


In [ ]:
train.loc[train["Embarked"] == "S", "Embarked"] = 0
train.loc[train["Embarked"] == "C", "Embarked"] = 1
train.loc[train["Embarked"] == "Q", "Embarked"] = 2
print(train["Embarked"])
print("T9)mode is "+str(train["Embarked"].mode()[0]))

0      0
1      1
2      0
3      0
4      0
      ..
886    0
887    0
888    0
889    1
890    2
Name: Embarked, Length: 891, dtype: object
T9)mode is 0


In [ ]:
train.loc[train["Sex"] == "female", "Sex"] = 0
train.loc[train["Sex"] == "male", "Sex"] = 1
print(train["Sex"])

0        male
1      female
2      female
3      female
4        male
        ...  
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: object
0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: object


In [157]:
def h(x):
    return 1/(1+math.e**(-x))

def dj_dtheta(theta,X,Y,j):
    result=0
    for i in range(np.size(Y)):
        result+=((Y[i]-h(np.dot(theta,X[i])))*X[i,j])
    print(result)
    return result

def grad_des(X,Y,theta):
    alpha=0.0001
    
    for i in range(200000):
        new_theta=[]
        if(i%20000==0):
            print(theta)
        for i in range(np.size(X[0])):
            a=theta[i]+alpha*dj_dtheta(theta,X,Y,i)
            new_theta.append(a)
        theta=np.array(new_theta)
    return theta

In [158]:
data = np.array(train[["Pclass","Sex","Age","Embarked"]].values, dtype = float)
data=np.insert(data, 0, 1, axis=1)
print(data)

[[ 1.  3.  1. 22.  0.]
 [ 1.  1.  0. 38.  1.]
 [ 1.  3.  0. 26.  0.]
 ...
 [ 1.  3.  0. 28.  0.]
 [ 1.  1.  1. 26.  1.]
 [ 1.  3.  1. 32.  2.]]


In [160]:
theta=grad_des(data,train["Survived"],np.zeros(np.size(data[0])))

[0. 0. 0. 0. 0.]
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan


KeyboardInterrupt: 