In [65]:
import pandas as pd
import numpy as np

In [66]:
train_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/train.csv"
train = pd.read_csv(train_url) #training set
test_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/test.csv"
test = pd.read_csv(test_url) #test set
print(train.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [67]:
# print("T8) median is "+str(train["Age"].median()))
# #print("mode is "+str(train["Age"].mode()[0]))

train["Age"] = train["Age"].fillna(train["Age"].median())


In [68]:
train.loc[train["Embarked"] == "S", "Embarked"] = 0
train.loc[train["Embarked"] == "C", "Embarked"] = 1
train.loc[train["Embarked"] == "Q", "Embarked"] = 2
train["Embarked"] = train["Embarked"].fillna(train["Embarked"].mode()[0])
print(train["Embarked"].value_counts(dropna=False))
print("T9)mode is "+str(train["Embarked"].mode()[0]))

0    646
1    168
2     77
Name: Embarked, dtype: int64
T9)mode is 0


In [69]:
train.loc[train["Sex"] == "female", "Sex"] = 0
train.loc[train["Sex"] == "male", "Sex"] = 1
print(train["Sex"].value_counts(dropna=False))

1    577
0    314
Name: Sex, dtype: int64


In [70]:
def h(x):
    return 1/(1+np.exp(-x))

def dj_dtheta(theta,X,Y,j):
    result=0
    for i in range(np.size(Y)):
        error=Y[i]-h(np.dot(theta,X[i]))
        result+=(error*X[i,j])
    return result

def grad_des(X,Y,theta):
    lnr=0.0001
    
    for i in range(30000):
        if(i%1000==0):
            print(i/1000,theta)
        new_theta=[]
        for j in range(5):
            a=theta[j]+lnr*dj_dtheta(theta,X,Y,j)
            new_theta.append(a)
        theta=np.array(new_theta)
        
    return theta
    
    

In [71]:
data = np.array(train[["Pclass","Sex","Age","Embarked"]].values, dtype = float)
data=np.insert(data, 0, 1, axis=1)
print(data)

[[ 1.  3.  1. 22.  0.]
 [ 1.  1.  0. 38.  1.]
 [ 1.  3.  0. 26.  0.]
 ...
 [ 1.  3.  0. 28.  0.]
 [ 1.  1.  1. 26.  1.]
 [ 1.  3.  1. 32.  2.]]


In [72]:
theta=np.array([1,5,8,6,5])
Y=np.array(train["Survived"].values, dtype = float)
theta=grad_des(data,Y,theta)
print("theta",theta)

0.0 [1 5 8 6 5]
1.0 [ 2.2953433  -2.33301091 -2.5302774   0.06393737  3.89352347]
2.0 [ 5.52397597 -2.51871699 -8.40716203  0.45461146  3.95331659]
3.0 [  8.34350133  -2.31998184 -11.07558085   0.2340718    3.56174382]
4.0 [ 10.60826277  -3.07416537 -12.4558304   -0.20246305   3.25272194]
5.0 [ 12.63521368  -3.45921736 -12.58538813   0.10961305   2.98354094]
6.0 [ 14.42358448  -3.84075244 -12.66050456  -0.95833586   2.78244703]
7.0 [ 16.11287881  -4.01427661 -12.83250164  -0.13225029   2.67281009]
8.0 [ 17.48368396  -4.46968714 -12.67402929   0.0283368    2.55137858]
9.0 [ 18.73678851  -4.69593729 -12.78139603  -1.0821609    2.43292795]
10.0 [ 19.87701328  -4.85494819 -12.85547099  -0.10133317   2.35748581]
11.0 [ 20.89548732  -4.94619334 -13.05130776  -0.04264805   2.24139677]
12.0 [ 21.70992147  -5.18563303 -12.9602479    0.18506151   2.14243739]
13.0 [ 22.39305499  -5.44762915 -12.95054655  -0.79153542   2.06096822]
14.0 [ 23.01724183  -5.58741143 -12.90587723  -0.13826283   2.00075

In [73]:
def isSurvived(theta,X,m):
    result=[]
    for i in range(m):
        ans=h(np.dot(theta,X[i]))
        if(ans>=0.5):
            ans=1
        else:
            ans=0
        result.append(ans)
    return result
        

dic=dict()
dic["PassengerId"]=np.array(test["PassengerId"].values, dtype = int)
test.loc[test["Sex"] == "female", "Sex"] = 0
test.loc[test["Sex"] == "male", "Sex"] = 1
test.loc[test["Embarked"] == "S", "Embarked"] = 0
test.loc[test["Embarked"] == "C", "Embarked"] = 1
test.loc[test["Embarked"] == "Q", "Embarked"] = 2
data=np.array(test[["Pclass","Sex","Age","Embarked"]].values, dtype = float)
data=np.insert(data, 0, 1, axis=1)
dic["Survived"]=isSurvived(theta,data,1309-892+1)
df=pd.DataFrame(dic)
df.to_csv("output.csv",index=False)






