In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
train_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/train.csv"
train = pd.read_csv(train_url) #training set
test_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/test.csv"
test = pd.read_csv(test_url) #test set
print(train.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [3]:
# print("T8) median is "+str(train["Age"].median()))
# #print("mode is "+str(train["Age"].mode()[0]))

train["Age"] = train["Age"].fillna(train["Age"].median())


In [4]:
train.loc[train["Embarked"] == "S", "Embarked"] = 0
train.loc[train["Embarked"] == "C", "Embarked"] = 1
train.loc[train["Embarked"] == "Q", "Embarked"] = 2
train["Embarked"] = train["Embarked"].fillna(train["Embarked"].mode()[0])
print(train["Embarked"].value_counts(dropna=False))
print("T9)mode is "+str(train["Embarked"].mode()[0]))

0    646
1    168
2     77
Name: Embarked, dtype: int64
T9)mode is 0


In [5]:
train.loc[train["Sex"] == "female", "Sex"] = 0
train.loc[train["Sex"] == "male", "Sex"] = 1
print(train["Sex"].value_counts(dropna=False))

1    577
0    314
Name: Sex, dtype: int64


In [6]:
def h(x):
    return 1/(1+np.exp(-x))

def dj_dtheta(theta,X,Y,j):
    result=0
    for i in range(np.size(Y)):
        error=Y[i]-h(np.dot(theta,X[i]))
        result+=(error*X[i,j])
    return result

def grad_des(X,Y,theta):
    lnr=0.0001
    
    for i in range(10000):
        print(i/100,theta)
        new_theta=[]
        for j in range(5):
            a=theta[j]+lnr*dj_dtheta(theta,X,Y,j)
            new_theta.append(a)
        theta=np.array(new_theta)
        
    return theta
    
    

In [7]:
data = np.array(train[["Pclass","Sex","Age","Embarked"]].values, dtype = float)
data=np.insert(data, 0, 1, axis=1)
print(data)

[[ 1.  3.  1. 22.  0.]
 [ 1.  1.  0. 38.  1.]
 [ 1.  3.  0. 26.  0.]
 ...
 [ 1.  3.  0. 28.  0.]
 [ 1.  1.  1. 26.  1.]
 [ 1.  3.  1. 32.  2.]]


In [8]:
theta=np.array([1,5,8,6,5])
Y=np.array(train["Survived"].values, dtype = float)
theta=grad_des(data,Y,theta)
print("theta",theta)

0.0 [1 5 8 6 5]
0.01 [0.9451  4.861   7.9532  4.35145 4.9831 ]
0.02 [0.8902 4.722  7.9064 2.7029 4.9662]
0.03 [0.8353  4.583   7.8596  1.05435 4.9493 ]
0.04 [ 0.78040006  4.44400006  7.8128     -0.59419989  4.9324    ]
0.05 [ 0.76457404  4.37331665  7.7850344  -0.75146177  4.92363708]
0.06 [ 0.76237092  4.33699344  7.76761497 -0.52429311  4.9187682 ]
0.07 [ 0.74175509  4.25525862  7.73656532 -0.83085045  4.90900799]
0.08 [ 0.74824553  4.24334146  7.72604967 -0.36980439  4.90770801]
0.09 [ 0.71433023  4.13450776  7.68687455 -1.12893399  4.8950304 ]
0.1 [ 0.73655444  4.16768863  7.68982576 -0.29230439  4.90429753]
0.11 [ 0.69593773  4.04775867  7.64720346 -1.31174587  4.89005309]
0.12 [ 0.72216675  4.09266385  7.65335414 -0.39867751  4.90200374]
0.13 [ 0.69155767  3.99009243  7.61589855 -1.04244147  4.88997525]
0.14 [ 0.7111513   4.01559272  7.61643208 -0.26662136  4.89649689]
0.15 [ 0.66878559  3.8930591   7.57288618 -1.36130043  4.88182511]
0.16 [ 0.69580948  3.94027995  7.57950531 -0.