In [18]:
import pandas as pd
import numpy as np

In [20]:
train_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/train.csv"
train = pd.read_csv(train_url) #training set
test_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/test.csv"
test = pd.read_csv(test_url) #test set

In [21]:
train["Age"] = train["Age"].fillna(train["Age"].median())

In [22]:
train.loc[train["Embarked"] == "S", "Embarked"] = 0
train.loc[train["Embarked"] == "C", "Embarked"] = 1
train.loc[train["Embarked"] == "Q", "Embarked"] = 2
train["Embarked"] = train["Embarked"].fillna(train["Embarked"].mode()[0])

In [23]:
train.loc[train["Sex"] == "female", "Sex"] = 0
train.loc[train["Sex"] == "male", "Sex"] = 1

In [24]:
def h(x):
    return 1/(1+np.exp(-x))

def dj_dtheta(theta,X,Y,j):
    result=0
    for i in range(np.size(Y)):
        error=Y[i]-h(np.dot(theta,X[i]))
        result+=(error*X[i,j])
    return result

def grad_des(X,Y,theta):
    lnr=0.0001
    epoch=50000
    for i in range(epoch):
        if(i%5000==0):
            print(i,theta)
        new_theta=[]
        for j in range(3):
            a=theta[j]+lnr*dj_dtheta(theta,X,Y,j)
            new_theta.append(a)
        theta=np.array(new_theta)
        
    return theta
    
    

In [25]:
data = np.array(train[["Sex","Age"]].values, dtype = float)
data=np.insert(data, 0, 1, axis=1)
normalizer=max(data[:,[2]])
data[:,[2]]=data[:,[2]]/normalizer
print(data)

[[1.    1.    0.275]
 [1.    0.    0.475]
 [1.    0.    0.325]
 ...
 [1.    0.    0.35 ]
 [1.    1.    0.325]
 [1.    1.    0.4  ]]


In [26]:
theta=np.array([0,0,0])
Y=np.array(train["Survived"].values, dtype = float)
theta=grad_des(data,Y,theta)
print("theta",theta)

0 [0 0 0]
5000 [ 1.14283205 -2.50497632 -0.25348763]
10000 [ 1.1811918  -2.50520938 -0.35604868]
15000 [ 1.18822401 -2.5052932  -0.37479815]
20000 [ 1.18951411 -2.50530997 -0.37823608]
25000 [ 1.18975082 -2.50531309 -0.37886681]
30000 [ 1.18979425 -2.50531366 -0.37898254]
35000 [ 1.18980222 -2.50531377 -0.37900377]
40000 [ 1.18980368 -2.50531379 -0.37900767]
45000 [ 1.18980395 -2.50531379 -0.37900838]
theta [ 1.189804   -2.50531379 -0.37900851]


In [27]:
def isSurvived(theta,X,m):
    result=[]
    for i in range(m):
        ans=h(np.dot(theta,X[i]))
        if(ans>=0.5):
            ans=1
        else:
            ans=0
        result.append(ans)
    return result
        

dic=dict()
dic["PassengerId"]=np.array(test["PassengerId"].values, dtype = int)
test.loc[test["Sex"] == "female", "Sex"] = 0
test.loc[test["Sex"] == "male", "Sex"] = 1
data=np.array(test[["Sex","Age"]].values, dtype = float)
data=np.insert(data, 0, 1, axis=1)
data[:,[2]]=data[:,[2]]/normalizer
dic["Survived"]=isSurvived(theta,data,418)
df=pd.DataFrame(dic)
df.to_csv("T13.csv",index=False)








In [29]:
def accuracy(theta,X,Y):
    count=0
    for i in range(np.size(Y)):
        predY=h(np.dot(theta,X[i]))
        if(predY>=0.5):
            predY=1
        else:
            predY=0
        
        if(predY==Y[i]):
            count+=1
    print(count/np.size(Y))
    
    
data = np.array(train[["Sex","Age"]].values, dtype = float)
data=np.insert(data, 0, 1, axis=1)
normalizer=max(data[:,[2]])
data[:,[2]]=data[:,[2]]/normalizer
Y=np.array(train["Survived"].values, dtype = float)
accuracy(theta,data,Y)

0.7867564534231201
